name: Cucumber and Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run all Cucumber tests
      - name: Run All Cucumber Tests
        run: npx cucumber-js

      # Run Web Tests
      - name: Run Web Tests
        if: ${{ github.event_name == 'push' }}
        run: npx cucumber-js --tags "@web"

      # Run API Tests
      - name: Run API Tests
        if: ${{ github.event_name == 'pull_request' }}
        run: npx cucumber-js --tags "@api"

      # Upload Cucumber Report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cucumber-report
          path: reports/cucumber-report/CucumberReport.html
          retention-days: 30
