# GitHub Actions Workflow: Automate Web & API Tests with Cucumber.js

name: Test Automation
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache node_modules to speed up future builds
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run all cucumber Scenarios
      - name: Run Cucumber Tests
        run: npx cucumber-js ./tests/features

      # Alternatively, run api tests with @api tag
      # - name: Run API Tests
      #   run: npx cucumber-js --tags '@web' ./tests/features

      # To run web tests with  @web tag
      # - name: Run web Tests
      #   run: npx cucumber-js --tags '@web' ./tests/features

      # Run All tests in parallel for faster execution (optional)
      # - name: Run Tests in Parallel
      #   run: npx cucumber-js --parallel 4 ./tests/features

      # Upload the Cucumber test report as an artifact
      - name: Upload Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report/
